ApproachingMastery/Controllers/SignUpController.cs
using DatabaseInteraction;
using DatabaseInteraction.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;

namespace ApproachingMastery.Controllers
{
    public class SignUpController : Controller
    {
        public ActionResult Index(UserLogin model = null)
        {
            if (model == null) model = new UserLogin();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EmailCheck(FormCollection col)
        {

            UserLogin model = new UserLogin() { Email = col["Email"] };

            if (!UserLoginController.VerifyCaptcha(Request["g-recaptcha-response"]))
                return View(nameof(Index), model);

            const string expression = @"^([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5})$";
            Regex re = new Regex(expression);
            if (!re.IsMatch(model.Email))
                return View(nameof(Index), model);

            string domain = model.Email.Substring(model.Email.IndexOf("@") + 1);
            if (SchoolDistrict.CheckDomainExists(domain))
            {
                Models.AddEditAccount account = new Models.AddEditAccount()
                {
                    UserLogin = model
                };
                Session["EmailAddress"] = model.Email;
                return View(nameof(CreateAccount), account);
            }
            return View(nameof(Index), model);
        }

        public ActionResult CreateAccount()
        {
            /*if (Session["EmailAddress"] == null) return RedirectToAction(nameof(Index));*/
            return View(new Models.AddEditAccount());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateAccount(FormCollection col)
        {
            UserLogin ul = new UserLogin()
            {
                Email = Session["EmailAddress"].ToString(),
                Password = col["UserLogin.Password"],
            };
            User user = new User()
            {
                FirstName = col["UserInformation.FirstName"],
                MiddleName = col["UserInformation.MiddleName"],
                LastName = col["UserInformation.LastName"],
                PhoneNumber = col["UserInformation.PhoneNumber"]
            };

            

            if (!ul.CreateNewAccount(HelperFunctions.GetClientIPAddress(Request), user))
            {
                ViewBag.ErrorMessage = "Could not create your account, please verify that your information is correct and try again";
                return View(new Models.AddEditAccount()
                {
                    UserLogin = ul,
                    UserInformation = user
                });
            }
            else
            {
                Session["EmailAddress"] = null;
                Session["UserID"] = ul.UserID;
                string messageText = "";
                string path = System.Web.HttpContext.Current.Server.MapPath("~/Views/EmailTemplates/ConfirmAccount.html");
                using (System.IO.StreamReader sr = new System.IO.StreamReader(path))
                {
                    messageText = sr.ReadToEnd();
                    sr.Close();
                }

                messageText = messageText.Replace("<guid_here>", ul.EmailValidationID.ToString());

                Emailer.SendEmail(Emailer.Senders.DoNotReply, ul.Email, "Confirm Email Address", messageText, true);
                return RedirectToAction(nameof(Confirm));
            }
        }
        public ActionResult Confirm()
        {
            UserLogin ul = new UserLogin();
            if (Request["guid"] != null)
            {
                ul = new UserLogin() { EmailValidationID = Guid.Parse(Request["guid"].ToString()) };
                ul.ConfirmEmail();
            }
            return View(ul);
        }

        public ActionResult EditAccount()
        {
            if (Session["LOGIN_ID"] == null) throw new Exception("Session id cannot be null");
            DatabaseInteraction.Models.User u;
            DatabaseInteraction.Models.User.GetUser((Guid)Session["LOGIN_ID"], out u);
            return View(u);
        }
        [HttpPost]
        public ActionResult EditAccount(Models.AddEditAccount ca)
        {
            if (Session["LOGIN_ID"] == null) throw new Exception("Session id cannot be null");
            
            if (ModelState.IsValid)
            {
                ca.UserInformation.UserLoginID = (Guid)Session["LOGIN_ID"];
                ca.UserInformation.UpdateUserInformation();
                User u;
                DatabaseInteraction.Models.User.GetUser(ca.UserInformation.UserLoginID, out u);
                ca.UserInformation = u;
            }
            return Json(ca);
        }
    }
}

ApproachingMastery/Controllers/UserLoginController.cs
using DatabaseInteraction;
using DatabaseInteraction.Models;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;

namespace ApproachingMastery.Controllers
{
    public class UserLoginController : Controller
    {
        // GET: UserLogin
        public ActionResult UserLogin()
        {
            return View(new DatabaseInteraction.Models.UserLogin());
        }

        [HttpPost]
        public ActionResult UserLogin(FormCollection col)
        {
            if (Session["LOGIN_ID"] != null)
                RedirectToAction("Dashboard", "User");
            if (!VerifyCaptcha(Request["g-recaptcha-response"]))
            {
                RedirectToAction(nameof(UserLogin));
            }


            DatabaseInteraction.Models.UserLogin li = new DatabaseInteraction.Models.UserLogin()
            {
                Password = col["Password"],
                Email = col["Email"]
            };

            LoginResult loginResult = li.Login(Request.UserHostAddress);

            switch (loginResult)
            {
                case LoginResult.Success:
                    Session["LOGIN_ID"] = li.UserID;
                    return RedirectToAction("Dashboard", "Home");
            }
            return RedirectToAction("../Home/Index", new { ShowLogin = 1 });
        }

        internal static bool VerifyCaptcha(string encodedResponse)
        {
            string secretKey = "6LdUAZgUAAAAAAR-xgGk7Sen9pBvjNacc0iu0dW_";
            bool result = false;
            string captchaAPIUri = $"https://www.google.com/recaptcha/api/siteverify?secret={secretKey}&response={encodedResponse}";
            HttpWebRequest request = (HttpWebRequest)WebRequest.Create(captchaAPIUri);
            using (WebResponse response = request.GetResponse())
            {
                using (StreamReader stream = new StreamReader(response.GetResponseStream()))
                {
                    JObject jResponse = JObject.Parse(stream.ReadToEnd());
                    var isSuccess = jResponse.Value<bool>("success");
                    result = isSuccess;
                }
            }
            return result;
        }

        public ActionResult ForgotPassword()
        {
            return View(new DatabaseInteraction.Models.UserLogin());
        }

        [HttpPost]
        public ActionResult ForgotPassword(FormCollection col)
        {
            DatabaseInteraction.Emailer.SendEmail(DatabaseInteraction.Emailer.Senders.DoNotReply, col["Email"], "Forgot Password", "test", false);
            return RedirectToAction("../Home/Index");
        }

        public ActionResult AddPassword(UserLogin ul)
        {
            return View(ul);
        }

      

        public ActionResult EditUserPassword()
        {
            if (Session["LOGIN_ID"] == null) return new HttpUnauthorizedResult();
            return View(new UserLogin() { IsEditing = true });
        }

        [HttpPost]
        public ActionResult EditUserPassword(UserLogin ul)
        {
            if (Session["LOGIN_ID"] == null) return new HttpUnauthorizedResult();
            ul.UserID = (Guid)Session["LOGIN_ID"];
            DatabaseInteraction.Models.UserLogin temp;
            DatabaseInteraction.Models.UserLogin.GetUserLogin(ul.UserID, out temp);
            temp.Password = ul.ExistingPassword;
            if (temp.Login(Request.UserHostAddress)==LoginResult.Success)
            {
                ul.Email = temp.Email;
                ul.RoleID = temp.RoleID;

                PasswordResetResult result = ul.UpdatePassword(Request.UserHostAddress);

                if (result==PasswordResetResult.Success)
                {
                    return Json(new { PasswordResult = "Success"});
                }
                else
                {
                    string errorMessage = result == PasswordResetResult.PreviousPassword ? "The new password cannot match any of your 7 last password" : "Unkown error updating password";
                    return Json(new { PasswordResult = "Error", ErrorMessage=errorMessage });
                }
            }
            else
            {
                return Json(new { PasswordResult = "Error", ErrorMessage = "Invalid Password" });
            }
        }

    }

}

ApproachingMastery/Views/UserLogin/AddPassword.cshtml
@using DatabaseInteraction.Models
@model UserLogin

@{
    Layout = null;
}


<link rel="stylesheet" type="text/css" href="~/Content/approaching-mastery_forms.css" />


<script>
    function showPassword() {

        var userInfo = $('#UpdatePassword');
        var button = $('#EditClosePassword');
        userInfo.toggle();
        if (userInfo.css('display') == 'block') button.prop('innerText', 'Close');
        else button.prop('innerText', 'Edit');
    }

    function passwordResult(data) {
        $('ExistingPassword').val("");
        $('Password').val("");
        $('ConfirmPassword').val("");
        if (data.PasswordResult == 'Success') alert("Password Updated Successfully!");
        else ("Error updating password");
    }

</script>

<link rel="stylesheet" type="text/css" href="~/Content/approaching-mastery_forms.css" />
<div class="editHeader">
    <table style="width:100%;">
        <tr>
            <td style="text-align:left">
                <h6 style="margin-left:10px;">Password</h6>
            </td>
            <td style="text-align:right;">
                <button id="EditClosePassword" onclick="showPassword();">Edit</button>
            </td>
        </tr>
    </table>
    <hr />
    @{
        string action = Model.IsEditing ? "EditUserPassword" : "AddPassword";
        using (Html.BeginForm(action, "UserLogin", FormMethod.Post))
        {
            <div id="UpdatePassword" class="editor">
                @Html.AntiForgeryToken()
                @Html.HiddenFor(m => m.IsEditing)

                <div class="inputBox" style="display:block;">
                    @Html.LabelFor(m => m.ExistingPassword)
                    @Html.PasswordFor(m => m.ExistingPassword)
                </div>
                <div class="inputBox" style="display:block;">
                    @Html.LabelFor(m => m.Password)
                    @Html.PasswordFor(m => m.Password)
                </div>
                <div class="inputBox" style="display:block;">
                    @Html.LabelFor(m => m.ConfirmPassword)
                    @Html.PasswordFor(m => m.ConfirmPassword)
                </div>
                @{ if (Model.IsEditing)
                    {
                        <div style="text-align:right;">
                            <button>Save Changes</button>
                        </div>
                    }
                }
            </div>
                    }
    }
</div>

ApproachingMastery/Views/UserLogin/EditUserPassword.cshtml
@using DatabaseInteraction.Models
@model UserLogin

@{
    Layout = "";
}


<link rel="stylesheet" type="text/css" href="~/Content/approaching-mastery_forms.css" />


<script>
    function showPassword() {

        var userInfo = $('#UpdatePassword');
        var button = $('#EditClosePassword');
        userInfo.toggle();
        if (userInfo.css('display') == 'block') button.prop('innerText', 'Close');
        else button.prop('innerText', 'Edit');
    }

    function passwordResult(data) {
        $('ExistingPassword').val("");
        $('Password').val("");
        $('ConfirmPassword').val("");
        if (data.PasswordResult == 'Success') alert("Password Updated Successfully!");
        else ("Error updating password");
    }

</script>

<link rel="stylesheet" type="text/css" href="~/Content/approaching-mastery_forms.css" />
<div class="editHeader">
    <table style="width:100%;">
        <tr>
            <td style="text-align:left">
                <h6 style="margin-left:10px;">Password</h6>
            </td>
            <td style="text-align:right;">
                <button id="EditClosePassword" onclick="showPassword();">Edit</button>
            </td>
        </tr>
    </table>
    <hr />
    @{
        string action = Model.IsEditing ? "EditUserPassword" : "AddPassword";
        using (Ajax.BeginForm(action, "UserLogin", new AjaxOptions { HttpMethod = "POST", OnSuccess = "passwordResult" }))
        {
        <div id="UpdatePassword" class="editor">
            @Html.AntiForgeryToken()
            @Html.HiddenFor(m => m.IsEditing)

            <div class="inputBox" style="display:block;">
                @Html.LabelFor(m => m.ExistingPassword)
                @Html.PasswordFor(m => m.ExistingPassword)
            </div>
            <div class="inputBox" style="display:block;">
                @Html.LabelFor(m => m.Password)
                @Html.PasswordFor(m => m.Password)
            </div>
            <div class="inputBox" style="display:block;">
                @Html.LabelFor(m => m.ConfirmPassword)
                @Html.PasswordFor(m => m.ConfirmPassword)
            </div>
            @{ if (Model.IsEditing)
                {
                    <div style="text-align:right;">
                        <button>Save Changes</button>
                    </div>
                }
            }
        </div>
        }
    }
</div>

ApproachingMastery/Views/UserLogin/ForgotPassword.cshtml
@model DatabaseInteraction.Models.UserLogin
@{
    ViewBag.Title = "Forgot Password";
    Layout = "~/Views/Shared/NoUser.cshtml";
}

<h2>Forgot Password</h2>
@using (Html.BeginForm(/*"ForgotPassword", "UserLogin",*/ FormMethod.Post))
{
    @Html.LabelFor(m => m.Email)
    @Html.TextBoxFor(m => m.Email)
    <button id="Reset" value="Reset">Reset Password</button>
}

ApproachingMastery/Views/UserLogin/UserLogin.cshtml
@model  DatabaseInteraction.Models.UserLogin
@{
    Layout = "";
}



@using (Html.BeginForm("UserLogin","UserLogin", FormMethod.Post, new { @id="loginForm"}))
{
    
    <!--<script type="text/javascript">
        grecaptcha.ready(function ()
        {
            grecaptcha.execute('6LcVAJgUAAAAAPXPwBSXPRzc7W8UnHC4KQPvHKE-', { action: 'login_view' }).then(function (token)
            {

            });
        });
    </script>-->
    <div class="modal-content animate">
        <div class="modal-header">
            <h4 class="modal-title">Sign in to start your session</h4>
        </div>

        <div class="container" style="width: 100%;">
            @Html.LabelFor(m => m.Email)
            @Html.TextBoxFor(m => m.Email)
            <br />
            @Html.LabelFor(m => m.Password)
            @Html.PasswordFor(m => m.Password)
            <script src="https://www.google.com/recaptcha/api.js" async defer></script>
            <script type="text/javascript">
                function onSubmit(token)
                {
                    document.getElementById("loginForm").submit();
                }
            </script>
            

            <button class="btn btn-success bootStrapButtons buttonAnimation g-recaptcha" data-sitekey="6LdUAZgUAAAAAPKz9tVKOmKcL-Ik6VQ7pCRmWngO" data-callback="onSubmit" type="submit"><span>Login</span></button>
                <!-- We Can add this later, Remember me button
        <label>
          <input type="checkbox" checked="checked" name="remember"> Remember me
        </label>
        -->
            </div>

        <div class="container" style="background-color:#f1f1f1; width: 100%;">
            <button type="button" onclick="document.getElementById('loginModal').style.display='none'" class="cancelbtn" value="Login">Cancel</button>
            <span class="psw">Forgot @Html.ActionLink("password?","ForgotPassword","UserLogin")</span>
        </div>
        <div class="container" style="background-color:#f1f1f1; width: 100%;">
            <span class="psw">Don't have an acount? @Html.ActionLink("Create one here!", "Index","SignUp")</span>
        </div>
    </div>
}