ApproachingMastery/ApproachingMastery/Controllers/StudentController.cs
using ApproachingMastery.Models;
using DatabaseInteraction.Models;
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ApproachingMastery.Controllers
{
    public class StudentController : Controller
    {

        #region Display/StudentViewer

        //Get: Display Student Name
        public ActionResult displayStudentName()
        {

            Guid studentID = Guid.Parse(Request["StudentID"]);
            Student s = new Student(studentID);
            return View(s.FirstName, s.LastName);
        }


        public ActionResult StudentViewer()
        {
            //User Info
            User u2 = new User();
            DatabaseInteraction.Models.User.GetUser((Guid)Session["LOGIN_ID"], out u2);
            ViewBag.UsersName = u2.FirstName;

            //Student Info
            if (Request["StudentID"] == null) throw new Exception("Student id cannot be null");
            Guid studentID = Guid.Parse(Request["StudentID"]);
            Student s;
            Student.GetStudent(studentID, out s);
            return View(s);
        }

        #endregion

        #region Add/Edit_Student

        // GET: Student
        public ActionResult AddStudent()
        {
            Guid currentUserID = new Guid(Session["LOGIN_ID"].ToString());
            AddEditStudentModal modal = new AddEditStudentModal(currentUserID);
            return View(modal);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddStudent(FormCollection col)
        {
            bool result = false;
            if (ModelState.IsValid)
            {
                Guid currentUserID = new Guid(Session["LOGIN_ID"].ToString());
                UserLogin ul = new UserLogin(currentUserID);

                string school = col["StudentSchool"];

                if (!Convert.ToBoolean(col["AddExistingStudent"]))
                {
                    result = ul.AddStudent(new Student(col["NewStudent.FirstName"], col["NewStudent.MiddleName"], col["NewStudent.LastName"],
                        DateTime.ParseExact(col["NewStudent.Birthday"], "yyyy-MM-dd", CultureInfo.InvariantCulture),
                        col["NewStudent.GradeLevel"],
                        DateTime.ParseExact(col["NewStudent.IEPDueDate"], "yyyy-MM-dd", CultureInfo.InvariantCulture),
                        DateTime.ParseExact(col["NewStudent.ETRDueDate"], "yyyy-MM-dd", CultureInfo.InvariantCulture)), new Guid(col["StudentSchool"]));
                }
                else
                {
                    result = ul.AddStudent(new Student(new Guid(col["ExistingStudent"].ToString())), Guid.Empty);
                }
            }
            if (result) return Json(new { Success = true, Message = "Student Added Succesfully" }, JsonRequestBehavior.AllowGet);
            else return Json(new { Success = false, Message = "Error Adding Student" }, JsonRequestBehavior.AllowGet);

        }

        public ActionResult EditStudent(Guid studentID)
        {
            AddEditStudentModal aesm = new AddEditStudentModal((Guid)Session["LOGIN_ID"]);
            Student s;
            Student.GetStudent(studentID, out s);
            aesm.NewStudent = s;
            aesm.IsEditing = true;
            return View(aesm);
        }

        [HttpPost]
        public ActionResult EditStudent(AddEditStudentModal aesm)
        {

            if (aesm.NewStudent.AddUpdateStudent())
                return Json(new { Success = true, Message = "Student updated succesfully" }, JsonRequestBehavior.AllowGet);
            else return Json(new { Success = false, Message = "Error updating student" }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult UpdateDueDates(FormCollection col)
        {
            NameValueCollection request = HttpUtility.ParseQueryString(Request.UrlReferrer.Query);
            if (request["StudentID"] == null) throw new Exception("Student ID cannot be null");

            Student s;
            Student.GetStudent(new Guid(request["StudentID"]), out s);

            s.IEPDueDate = DateTime.ParseExact(col["IEPDueDate"], "yyyy-MM-dd", CultureInfo.InvariantCulture);
            s.ETRDueDate = DateTime.ParseExact(col["ETRDueDate"], "yyyy-MM-dd", CultureInfo.InvariantCulture);
            s.AddUpdateStudent();
            return Redirect(Request.UrlReferrer.ToString());
        }



        #endregion

        #region Assignments

        //Get: Assignment Evaluation Tests
        public ActionResult Assignment()
        {
            return View();
        }

        #endregion

        #region Add/Edit Goals

        public JsonResult AddAcademicGoal()
        {
            if (Session["LOGIN_ID"] == null) throw new Exception("Not Authorized");
            Student s;
            if (!GetStudentFromReferrer(out s))
            {
                return Json(new { Success = false, Message = "Error getting current student" }, JsonRequestBehavior.AllowGet);
            }

            Goal g = new Goal()
            {
                GoalArea = GoalArea.Academic,
                DueDate = DateTime.Now + new TimeSpan(7, 0, 0, 0)
            };

            return Json(new { Success = true, html = RazorHelpers.RenderRazorViewToString(ControllerContext, "AddAcademicGoal", g) }, JsonRequestBehavior.AllowGet);
        }
        public JsonResult EditAcademicGoal(Guid goalID)
        {
            if (Session["LOGIN_ID"] == null) throw new Exception("Not Authorized");
            Student s;

            if (!GetStudentFromReferrer(out s))
            {
                return Json(new { Success = false, Message = "Error getting current student" }, JsonRequestBehavior.AllowGet);
            }
            if (s.GetAcademicGoals())
            {
                Goal g = s.AcademicGoals.Find(goal => goal.GoalID == goalID);
                return Json(new { Success = true, html = RazorHelpers.RenderRazorViewToString(ControllerContext, nameof(EditAcademicGoal), g) }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { Success = false, Message = "Error loading selected goal" }, JsonRequestBehavior.AllowGet);

        }

        [HttpPost]
        public JsonResult EditAcademicGoal(Goal goal)
        {
            if (Session["LOGIN_ID"] == null) throw new Exception("Not Authorized");
            Student s;

            if (!GetStudentFromReferrer(out s))
            {
                return Json(new { Success = false, Message = "Error getting current student" }, JsonRequestBehavior.AllowGet);
            }
            if (s.AddGoal(goal))
                return Json(new { Success = true, Message = "Goal Updated!" }, JsonRequestBehavior.AllowGet);
            return Json(new { Success = false, Message = "Error updating selected goal" }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult AddAcademicGoal(Goal g)
        {
            if (Session["LOGIN_ID"] == null) throw new Exception("Not Authorized");
            Student s;
            if (!GetStudentFromReferrer(out s))
            {
                return Json(new { Success = false, Message = "Error getting current student" }, JsonRequestBehavior.AllowGet);
            }
            g.AssignedBy = (Guid)Session["LOGIN_ID"];
            if (s.AddGoal(g))
                return Json(new { Success = true, Message = "New Goal Added" }, JsonRequestBehavior.AllowGet);
            return Json(new { Success = true, Message = "Error adding new goal" }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult DeleteAcademicGoal(Guid goalID)
        {
            Student s;
            if (!GetStudentFromReferrer(out s))
            {
                return Json(new { Success = false, Message = "Error getting current student" }, JsonRequestBehavior.AllowGet);
            }
            if (s.RemoveGoal(new Goal() { GoalID = goalID }))
                return Json(new { Success = true, Message = "Goal removed!" }, JsonRequestBehavior.AllowGet);
            return Json(new { Success = true, Message = "Error removing goal" }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult AddBehaviorGoal()
        {
            if (Session["LOGIN_ID"] == null) throw new Exception("Not Authorized");
            Student s;
            if (!GetStudentFromReferrer(out s))
            {
                return Json(new { Success = false, Message = "Error getting current student" }, JsonRequestBehavior.AllowGet);
            }

            Goal g = new Goal()
            {
                GoalArea = GoalArea.Behavioral,
                DueDate = DateTime.Now + new TimeSpan(7, 0, 0, 0)
            };

            return Json(new { Success = true, html = RazorHelpers.RenderRazorViewToString(ControllerContext, "AddBehaviorGoal", g) }, JsonRequestBehavior.AllowGet);
        }
        public JsonResult EditBehaviorGoal(Guid goalID)
        {
            if (Session["LOGIN_ID"] == null) throw new Exception("Not Authorized");
            Student s;

            if (!GetStudentFromReferrer(out s))
            {
                return Json(new { Success = false, Message = "Error getting current student" }, JsonRequestBehavior.AllowGet);
            }
            if (s.GetBehavioralGoals())
            {
                Goal g = s.BehavioralGoals.Find(goal => goal.GoalID == goalID);
                return Json(new { Success = true, html = RazorHelpers.RenderRazorViewToString(ControllerContext, nameof(EditBehaviorGoal), g) }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { Success = false, Message = "Error loading selected goal" }, JsonRequestBehavior.AllowGet);

        }

        [HttpPost]
        public JsonResult EditBehaviorGoal(Goal goal)
        {
            if (Session["LOGIN_ID"] == null) throw new Exception("Not Authorized");

ApproachingMastery/ApproachingMastery/Controllers/UserController.cs
using DatabaseInteraction.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ApproachingMastery.Controllers
{
    public class UserController : Controller
    {
        private bool GetUserID(out Guid userID)
        {
            userID = Guid.Empty;
            object sessionObject = Session["LOGIN_ID"];
            if (sessionObject == null) return false;
            userID = (Guid)sessionObject;
            return true;
        }


        // GET: User
        public ActionResult Dashboard()
        {
            Guid userID = Guid.Parse(Session["LOGIN_ID"].ToString());
            UserLogin ul = new UserLogin(userID);
            ul.GetLoginInfo();
            return View(ul);
        }

        public ActionResult GetStudents()
        {
            if (Session["Login_ID"] == null)
                return RedirectToAction("Index", "Home");
            Guid userID = Guid.Parse(Session["LOGIN_ID"].ToString());
            UserLogin ul = new UserLogin(userID);
            ul.GetStudents();
            return Json(new
            {
                StudentCount = ul.Students.Count,
                html = RazorHelpers.RenderRazorViewToString(ControllerContext, nameof(GetStudents), ul)
            },
            JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetTeachers()
        {
            if (Session["Login_ID"] == null)
                return RedirectToAction("Index", "Home");
            Guid userID = Guid.Parse(Session["Login_ID"].ToString());
            UserLogin ul = new UserLogin(userID);
            ul.GetTeachers();
            return View(ul);
        }

        public ActionResult DeactivateStudent()
        {
            if (Request["StudentID"] == null) throw new Exception("StudentID is null");
            if (Session["LOGIN_ID"] == null) throw new Exception("Login ID cannot be null");
            Guid studentID = new Guid(Request["StudentID"]);
            UserLogin ul = new UserLogin((Guid)Session["LOGIN_ID"]);


            if (ul.RemoveStudent(studentID))
            {
                return Json(new { status = "Removed" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { status = "Error removing student" }, JsonRequestBehavior.AllowGet);
            }

        }

        public ActionResult EditAccount()
        {
            Guid userID;
            if (!GetUserID(out userID)) return new HttpUnauthorizedResult();
            return View();
        }

        public ActionResult EditUserProfile()
        {
            Guid userID;
            if (!GetUserID(out userID)) return Json(new HttpUnauthorizedResult());
            DatabaseInteraction.Models.User u;
            if (DatabaseInteraction.Models.User.GetUser(userID, out u))
            {
                return View(u);
            }
            else
            {
                return Json("<div>Error retreiving user information</div>", JsonRequestBehavior.AllowGet);
            }

        }

        public ActionResult AddUser()
        {
            User u = new User();
            return View(u);
        }


        // Need Help Here
        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult EditUserProfile(User u)
        {
            Guid userID;
            if (!GetUserID(out userID)) return Json(new { UpdateStatus = "Error"});
            u.UserLoginID = userID;
            if(!u.UpdateUserInformation()) return Json(new { UpdateStatus = "Error"});
            return Json(new { UpdateStatus = "Success" });
        }

        public ActionResult GetCalendar()
        {


            return View();
        }
    }
}

ApproachingMastery/ApproachingMastery/Views/User/AddUser.cshtml
@using DatabaseInteraction.Models
@model User

@{
    Layout = null;
}


<link rel="stylesheet" type="text/css" href="~/Content/approaching-mastery_forms.css" />
<style>
    .editHeader {
        margin: 10px;
        border: 1px solid lightgrey;
    }

    .editor {
        display: none;
        padding: 10px;
        text-align: center;
    }
</style>
<div id="profileEditor">
    @{
        @Html.EditorFor(m => m);
    }
</div>

ApproachingMastery/ApproachingMastery/Views/User/Dashboard.cshtml
@using DatabaseInteraction.Models
@model UserLogin

@{

    Layout = "~/Views/Shared/_Layout.cshtml";

}

<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">


    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Dashboard</h1>
        </div>
    </div><!--/.row-->

    <div class="panel panel-container">
        <div class="row">
            <div class="col-xs-6 col-md-3 col-lg-3 no-padding">
                <div class="panel panel-teal panel-widget border-right">
                    <div class="row no-padding">
                        <em class="fas fa-chalkboard-teacher fa-2x color-blue "></em>
                        <!-- COUNT(intTeacherID) -->
                        <div class="large">4</div>
                        <div class="text-muted">Teachers</div>
                    </div>
                </div>
            </div>

            <div class="col-xs-6 col-md-3 col-lg-3 no-padding">
                <div class="panel panel-blue panel-widget border-right">
                    <div class="row no-padding">
                        <em class="fas fa-user-graduate fa-2x color-red"></em>
                        <!-- COUNT(intStudentID)-->
                        <div class="large">35</div>
                        <div class="text-muted">Students</div>
                    </div>
                </div>
            </div>
            <div class="col-xs-6 col-md-3 col-lg-3 no-padding">
                <div class="panel panel-orange panel-widget border-right">
                    <div class="row no-padding">
                        <em class="fas fa-tasks fa-2x color-green"></em>
                        <!-- COUNT(Goals)Where blnComplete = true(1)-->
                        <div class="large">67</div>
                        <div class="text-muted">Goals Met</div>
                    </div>
                </div>
            </div>
            <div class="col-xs-6 col-md-3 col-lg-3 no-padding">
                <div class="panel panel-red panel-widget ">
                    <div class="row no-padding">
                        <em class="fas fa-edit fa-2x color-orange"></em>

                        <div class="large">125</div>
                        <div class="text-muted">Goals Pending</div>
                    </div>
                </div>
            </div>
        </div><!--/.row-->
    </div>

    <!-- END TOP TABS -->
    <!-- START STUDENT TABLE -->

    <div class="panel panel-default">
        <div class="panel-heading">
            Students
                  
            <span class="pull-right clickable panel-toggle panel-button-tab-left"><em class="fa fa-toggle-up"></em></span>
        </div>

        <div class="panel-body">

            @{ Html.RenderAction("GetStudents", "User");}


            <div class="panel-footer">
                <div class="input-group">

                    <button class="btn btn-primary bootStrapButtons buttonAnimation" id="btnAddStudent" onclick="document.getElementById('addStudentModal').style.display = 'block'"><span>Add Student</span></button>

                </div>
            </div>
        </div>
    </div>

    <!-- END STUDENT TABLE -->

    <!-- START OTHER TEACHERS-->


    <div class="panel panel-default">
        <div class="panel-heading">
            Other Teachers

            <span class="pull-right clickable panel-toggle panel-button-tab-left"><em class="fa fa-toggle-up"></em></span>
        </div>
        <div class="panel-body">

            <div class="w3-container">

                @{ Html.RenderAction("GetTeachers", "User");}

            </div>

            <div class="panel-footer">
                <div class="input-group">

                </div>
            </div>
        </div>
    </div>

    <!-- END OTHER TEACHERS-->

</div>

<script src="~/js/jquery-1.11.1.min.js"></script>
<script src="~/js/bootstrap.min.js"></script>
<script src="~/js/bootstrap-datepicker.js"></script>
<script src="~/js/custom.js"></script>
<script>
		window.onload = function () {
	var chart1 = document.getElementById("line-chart").getContext("2d");
	window.myLine = new Chart(chart1).Line(lineChartData, {
	responsive: true,
	scaleLineColor: "rgba(0,0,0,.2)",
	scaleGridLineColor: "rgba(0,0,0,.05)",
	scaleFontColor: "#c5c7cc"
	});
};
</script>

<div id="addStudentModal" class="modal">

    @{Html.RenderAction("AddStudent", "Student");}

</div>



    </html>

ApproachingMastery/ApproachingMastery/Views/User/EditAccount.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script>
    $(document).ready(function () {
        loadUserInfo();
    });

    function loadUserInfo(d2) {
        var error = false;
        if (d2 != null) {
            if (d2.UpdateStatus == "Success") alert("User information updated successfully!");
            else alert("Error updating user information!");
        }
        $.ajax({
            type: 'GET',
            url: '/User/EditUserProfile',
            dataType: 'html',
            success: function (data) {
                var frame = $('#EditCloseUserInfo');
                var display = frame.css('display');
                $('#userEditor').html(data);
                if (error) showUserInfo();

            }
        });
    }
</script>
<style>
    .formBlock {
        width: 75%;
        border: 1px solid lightgray;
        text-align: center;
    }
</style>
<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main formBlock">
    <div id="userEditor">
    </div>
    <div>
        @{Html.RenderAction("EditUserPassword", "UserLogin");}
    </div>
</div>

ApproachingMastery/ApproachingMastery/Views/User/EditUserProfile.cshtml
@using DatabaseInteraction.Models
@model User

@{
    Layout = null;
}


<link rel="stylesheet" type="text/css" href="~/Content/approaching-mastery_forms.css" />
<style>
    .editHeader {
        margin: 10px;
        border: 1px solid lightgrey;
    }

    .editor {
        display: none;
        padding: 10px;
        text-align: center;
    }
</style>
<div id="profileEditor">
    @{
        Model.IsEditing = true;
        @Html.EditorFor(m => m);
    }
</div>

ApproachingMastery/ApproachingMastery/Views/User/GetCalendar.cshtml
@{
    Layout = null;
}

<style>
* {box-sizing: border-box;}
ul {list-style-type: none;}
body {font-family: Verdana, sans-serif;}

.month {
  padding: 20px 25px;
  width: 100%;
  background: #1abc9c;
  text-align: center;
}

.month ul {
  margin: 0;
  padding: 0;
}

.month ul li {
  color: white;
  font-size: 20px;
  text-transform: uppercase;
  letter-spacing: 3px;
}

.month .prev {
  float: left;
  padding-top: 10px;
}

.month .next {
  float: right;
  padding-top: 10px;
}

.weekdays {
  margin: 0;
  padding: 10px 0;
  background-color: #ddd;
}

.weekdays li {
  display: inline-block;
  width: 12.6%;
  color: #666;
  text-align: center;
}

.days {
  padding: 10px 0;
  background: #eee;
  margin: 0;
}

.days li {
  list-style-type: none;
  display: inline-block;
  width: 12.6%;
  text-align: center;
  margin-bottom: 5px;
  font-size:12px;
  color: #777;
}

.days li .active {
  padding: 5px;
  background: #1abc9c;
  color: white !important
}

</style>


<div class="month">
    <ul>
        <li class="prev">&#10094;</li>
        <li class="next">&#10095;</li>
        <li>
            April<br>
            <span style="font-size:18px">2019</span>
        </li>
    </ul>
</div>

<ul class="weekdays">
    <li>Mo</li>
    <li>Tu</li>
    <li>We</li>
    <li>Th</li>
    <li>Fr</li>
    <li>Sa</li>
    <li>Su</li>
</ul>

<ul class="days">
    <li>1</li>
    <li>2</li>
    <li>3</li>
    <li>4</li>
    <li>5</li>
    <li>6</li>
    <li>7</li>
    <li>8</li>
    <li>9</li>
    <li>10</li>
    <li>11</li>
    <li>12</li>
    <li>13</li>
    <li>14</li>
    <li>15</li>
    <li>16</li>
    <li>17</li>
    <li>18</li>
    <li>19</li>
    <li>20</li>
    <li>21</li>
    <li>22</li>
    <li>23</li>
    <li>24</li>
    <li><span class="active">25</span></li>
    <li>26</li>
    <li>27</li>
    <li>28</li>
    <li>29</li>
    <li>30</li>
    <li></li>
    <li></li>
</ul>

ApproachingMastery/ApproachingMastery/Views/User/GetStudents.cshtml
@using DatabaseInteraction.Models
@using System.Linq
@model UserLogin

@{
    Layout = null;
}

<script type="text/javascript">
    $(function () {
        $(".editStudent").click(function () {
            var $buttonClicked = $(this);
            var id = $buttonClicked.attr('data-id');
            $.ajax({
                type: "GET",
                url: editStudentURL,
                contentType: "application/json; charset=utf-8",
                data: { "studentID": id },
                datatype: "json",
                success: function (data) {
                    $('#editStudentContent').html(data);
                    //$('#EditStudentModal').modal(options);
                    //$('#EditStudentModal').style.display = 'block';
                    $('#EditStudentModal').modal('show');
                },
                error: function () {
                    alert("Error loading student data");
                }
            });
        });
    });

    $(function () {
    $(".deactivateStudent").click(function () {
        var $buttonClicked = $(this);
        var id = $buttonClicked.attr('data-id');
        //var options = { "backdrop": "static", keyboard: true };
        $.ajax({
            type: "GET",
            url: deleteStudentURL,
            contentType: "application/json; charset=utf-8",
            data: { "studentID": id },
            datatype: "json",
            success: function (data) {
                loadStudents();
            },
            error: function () {
                alert("Error loading student data");
                loadStudents();
            }
        });
    });
});


/**/</script>



<table class="w3-table w3-striped w3-white w3-hoverable sortable">
    <tr class="studentTableHeader">
        <th></th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Grade</th>
        <th>Edit</th>
        <th>Remove</th>
    </tr>
    @{
        foreach (Student s in Model.Students)
        {
            <tr>
                <td><i class="fa fa-user w3-text-blue w3-large"></i></td>
                <td onclick="location.href = '@(Url.Action("StudentViewer", "Student", new { StudentID = s.StudentID }))'">@s.FirstName </td>
                <td onclick="location.href = '@(Url.Action("StudentViewer", "Student", new { StudentID = s.StudentID }))'">@s.LastName</td>
                <td>@s.GradeLevel </td>
                <td><a href="javascript:void(0);" data-id="{@s.StudentID}" class="btn btn-danger editStudent"><i class="fas fa-pencil-alt"></i></a></td>
                <td><a href="javascript:void(0);" data-id="{@s.StudentID}" class="btn btn-danger deactivateStudent"><i class="fas fa-user-times"></i></a></td>
                <!--<td><button class="btn btn-danger" onclick="location.href = '@(Url.Action("DeactivateStudent", "User", new { StudentID = s.StudentID }))'"><i class="fas fa-user-times"></i></button> </td>-->
            </tr>
            }
            }
        </table>
        <div class="panel-footer">
            <div class="input-group">
                <button class="btn btn-primary bootStrapButtons buttonAnimation" id="btnAddStudent" onclick="AddStudent()"><span>Add Student</span></button>
            </div>
        </div>

ApproachingMastery/ApproachingMastery/Views/User/GetTeachers.cshtml
@using DatabaseInteraction.Models
@using System.Linq
@model UserLogin

@{ 
    Layout = null;
}


<ul class="w3-ul w3-card-4 w3-white">

    @{


        foreach (User s in Model.OtherTeachers)
        {

            <li class="w3-padding-16">

                <img src="~/Images/Dashboard/avatar2.png" class="w3-left w3-circle w3-margin-right" style="width:35px">
                <span class="w3-xlarge">Name: @s.FirstName  @s.LastName, Class: @s.Class, Phone: @s.PhoneNumber</span><br>

            </li>

        }
    }

    </ul>